name : Build application

on:
  workflow_dispatch:

jobs:
  build-be-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with: 
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push BE docker image
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ../Dockerfile
          target: prod-be
          push: true
          tags: | 
            ghcr.io/mistr-hnm/mypet-be:latest
            ghcr.io/mistr-hnm/mypet-be:${{ github.sha }}
 
  # deploy:
  #   runs-on: ubuntu-latest
    
  #   needs:
  #     - build-be-docker-image

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.5.3
  #       with:
  #         ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      
  #     - name: Add SSH host key
  #       run: ssh-keyscan -H mypet.devhnm.xyz >> ~/.ssh/known_hosts

  #     - name: Copy files to server
  #       run: |
  #         scp docker-compose.prod.yaml ubuntu@mypet.devhnm.xyz:/home/ubuntu/
  #         ssh ubuntu@mypet.devhnm.xyz "cat > /home/ubuntu/apps/mypet-be/.env" << 'EOF'
  #         ${{ secrets.BE_APP_ENV_FILE }}
  #         EOF
      
  #     - name: Log in to Container Registry on server and deploy
  #       run: |
  #         ssh ubuntu@mypet.devhnm.xyz <<EOF
  #           echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
  #           docker pull ghcr.io/mistr-hnm/mypet-be:latest
  #           docker compose -f /home/ubuntu/docker-compose.prod.yaml up -d --remove-orphans
  #         EOF



  